// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHC_kUyK4F4Z7jFTpBnAwyaU5kj4Y-Evs',
    appId: '1:304835023757:web:658190e94b1103331023c4',
    messagingSenderId: '304835023757',
    projectId: 'fir-tutorial-f9fea',
    authDomain: 'fir-tutorial-f9fea.firebaseapp.com',
    storageBucket: 'fir-tutorial-f9fea.appspot.com',
    measurementId: 'G-L3XR4W7YSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeay9ExrHzK34YE1Z-RjLoUvtfR9nBk4A',
    appId: '1:304835023757:android:ea95095d472f8caa1023c4',
    messagingSenderId: '304835023757',
    projectId: 'fir-tutorial-f9fea',
    storageBucket: 'fir-tutorial-f9fea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhOsv_oqmljpgvbVxI3y131xXNOYcApM',
    appId: '1:304835023757:ios:2443834e7929eab01023c4',
    messagingSenderId: '304835023757',
    projectId: 'fir-tutorial-f9fea',
    storageBucket: 'fir-tutorial-f9fea.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
